indent_style = "Block"
use_small_heuristics = "Default"
comment_width = 120
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 20
fn_single_line = true
where_single_line = true
imports_indent = "Visual"
imports_layout = "HorizontalVertical"
merge_imports = true
match_block_trailing_comma = true
merge_derives = true
newline_style = "Unix"
reorder_impl_items = true
struct_field_align_threshold = 20
use_field_init_shorthand = true
use_try_shorthand = true
format_doc_comments = true
wrap_comments = true
unstable_features = true
version = "Two"
control_brace_style = "AlwaysSameLine"
brace_style = "PreferSameLine"